name: Build with Webpack (Prod)

on:
    push:
        branches: [prod]
    pull_request:
        branches: [prod]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: prod

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm ci

            - name: Webpack Build
              env:
                  STAGE: prod
              run: npm run build

            - name: Check dist directory
              run: |
                  if [ ! -d "dist" ] || [ -z "$(ls -A dist)" ]; then
                    echo "Error: dist directory is missing or empty after build"
                    exit 1
                  fi

            - name: Trigger AWS deployment workflow (Prod)
              if: success()
              run: |
                  curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/${{ secrets.INFRA_REPO }}/dispatches \
                    -d '{"event_type":"frontend_source_updated_prod"}'
